- name: Installing httpd and firewalld
  ansible.builtin.package:
    name: "{{package}}"
    state: present

- name: Starting the service
  ansible.builtin.service:
    name: "{{package}}"
    state: started

- name: Enabling the service
  ansible.builtin.service:
    name: "{{package}}"
    enabled: true